// Package windowsoperator provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package windowsoperator

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ScreenshotFormat.
const (
	Jpeg ScreenshotFormat = "jpeg"
	Png  ScreenshotFormat = "png"
)

// ActionResult defines model for ActionResult.
type ActionResult struct {
	Message  string             `json:"message"`
	Metadata *map[string]string `json:"metadata"`
	Success  bool               `json:"success"`
}

// HealthResult defines model for HealthResult.
type HealthResult struct {
	CaptureBackends []string  `json:"captureBackends"`
	CheckedAtUtc    time.Time `json:"checkedAtUtc"`
	McpEnabled      bool      `json:"mcpEnabled"`
	Platform        string    `json:"platform"`
	RestBaseUrl     string    `json:"restBaseUrl"`
	RuntimeMode     string    `json:"runtimeMode"`
	Status          string    `json:"status"`
	UiBackend       string    `json:"uiBackend"`
}

// HotkeyRequest defines model for HotkeyRequest.
type HotkeyRequest struct {
	Keys *[]string `json:"keys,omitempty"`
}

// MailAttachmentRef defines model for MailAttachmentRef.
type MailAttachmentRef struct {
	Extension string `json:"extension"`
	FileName  string `json:"fileName"`
	Index     int32  `json:"index"`
	Size      *int64 `json:"size"`
}

// MailDownloadRequest defines model for MailDownloadRequest.
type MailDownloadRequest struct {
	AttachmentIndexes *[]int32   `json:"attachmentIndexes"`
	DryRun            *bool      `json:"dryRun,omitempty"`
	FolderPath        *string    `json:"folderPath"`
	Freshness         *string    `json:"freshness,omitempty"`
	MaxMessages       *int32     `json:"maxMessages,omitempty"`
	MessageIds        *[]string  `json:"messageIds"`
	ReceivedAfterUtc  *time.Time `json:"receivedAfterUtc"`
	ReceivedBeforeUtc *time.Time `json:"receivedBeforeUtc"`
	RunId             *string    `json:"runId"`
	SubjectContains   *string    `json:"subjectContains"`
}

// MailDownloadResult defines model for MailDownloadResult.
type MailDownloadResult struct {
	Actions            []string                `json:"actions"`
	AttachmentsSaved   int32                   `json:"attachmentsSaved"`
	AttachmentsSkipped int32                   `json:"attachmentsSkipped"`
	CompletedAtUtc     time.Time               `json:"completedAtUtc"`
	DownloadRoot       string                  `json:"downloadRoot"`
	Errors             []MailRunError          `json:"errors"`
	LastSyncUtc        *time.Time              `json:"lastSyncUtc"`
	MessagesMatched    int32                   `json:"messagesMatched"`
	MessagesScanned    int32                   `json:"messagesScanned"`
	Recovered          bool                    `json:"recovered"`
	RunId              string                  `json:"runId"`
	RunRoot            string                  `json:"runRoot"`
	Saved              []MailSavedAttachment   `json:"saved"`
	Skipped            []MailSkippedAttachment `json:"skipped"`
	Success            bool                    `json:"success"`
	Warnings           []string                `json:"warnings"`
}

// MailFolderRef defines model for MailFolderRef.
type MailFolderRef struct {
	ChildCount int32  `json:"childCount"`
	Depth      int32  `json:"depth"`
	Name       string `json:"name"`
	Path       string `json:"path"`
}

// MailFoldersResult defines model for MailFoldersResult.
type MailFoldersResult struct {
	Actions        []string        `json:"actions"`
	CompletedAtUtc time.Time       `json:"completedAtUtc"`
	Errors         []MailRunError  `json:"errors"`
	Folders        []MailFolderRef `json:"folders"`
	LastSyncUtc    *time.Time      `json:"lastSyncUtc"`
	Recovered      bool            `json:"recovered"`
	Success        bool            `json:"success"`
	Warnings       []string        `json:"warnings"`
}

// MailListFoldersRequest defines model for MailListFoldersRequest.
type MailListFoldersRequest struct {
	Freshness *string `json:"freshness,omitempty"`
}

// MailMessageRef defines model for MailMessageRef.
type MailMessageRef struct {
	AttachmentCount int32               `json:"attachmentCount"`
	Attachments     []MailAttachmentRef `json:"attachments"`
	FolderPath      string              `json:"folderPath"`
	MessageId       string              `json:"messageId"`
	ReceivedTime    *time.Time          `json:"receivedTime"`
	Subject         string              `json:"subject"`
}

// MailRunError defines model for MailRunError.
type MailRunError struct {
	Code    string  `json:"code"`
	Detail  *string `json:"detail"`
	Message string  `json:"message"`
}

// MailSavedAttachment defines model for MailSavedAttachment.
type MailSavedAttachment struct {
	AbsolutePath     string     `json:"absolutePath"`
	AlreadyProcessed bool       `json:"alreadyProcessed"`
	AttachmentIndex  int32      `json:"attachmentIndex"`
	Bytes            int64      `json:"bytes"`
	FileName         string     `json:"fileName"`
	FolderPath       string     `json:"folderPath"`
	MessageId        string     `json:"messageId"`
	ReceivedTime     *time.Time `json:"receivedTime"`
	RelativePath     string     `json:"relativePath"`
	Subject          string     `json:"subject"`
}

// MailSearchRequest defines model for MailSearchRequest.
type MailSearchRequest struct {
	FolderPath               *string    `json:"folderPath"`
	Freshness                *string    `json:"freshness,omitempty"`
	HasAttachments           *bool      `json:"hasAttachments"`
	IncludeAttachmentDetails *bool      `json:"includeAttachmentDetails,omitempty"`
	MaxResults               *int32     `json:"maxResults,omitempty"`
	ReceivedAfterUtc         *time.Time `json:"receivedAfterUtc"`
	ReceivedBeforeUtc        *time.Time `json:"receivedBeforeUtc"`
	SubjectContains          *string    `json:"subjectContains"`
}

// MailSearchResult defines model for MailSearchResult.
type MailSearchResult struct {
	Actions        []string         `json:"actions"`
	CompletedAtUtc time.Time        `json:"completedAtUtc"`
	Errors         []MailRunError   `json:"errors"`
	LastSyncUtc    *time.Time       `json:"lastSyncUtc"`
	Messages       []MailMessageRef `json:"messages"`
	Recovered      bool             `json:"recovered"`
	Success        bool             `json:"success"`
	Warnings       []string         `json:"warnings"`
}

// MailSkippedAttachment defines model for MailSkippedAttachment.
type MailSkippedAttachment struct {
	AttachmentIndex int32      `json:"attachmentIndex"`
	FileName        string     `json:"fileName"`
	FolderPath      string     `json:"folderPath"`
	MessageId       string     `json:"messageId"`
	Reason          string     `json:"reason"`
	ReceivedTime    *time.Time `json:"receivedTime"`
	Subject         string     `json:"subject"`
}

// MailStatusResult defines model for MailStatusResult.
type MailStatusResult struct {
	CheckedAtUtc         time.Time `json:"checkedAtUtc"`
	HeadlessOutlookCount int32     `json:"headlessOutlookCount"`
	LastWorkerError      *string   `json:"lastWorkerError"`
	VisibleOutlookCount  int32     `json:"visibleOutlookCount"`
	WorkerAvailable      bool      `json:"workerAvailable"`
}

// MicrosoftDeviceLoginRequest defines model for MicrosoftDeviceLoginRequest.
type MicrosoftDeviceLoginRequest struct {
	DeviceCode      *string `json:"deviceCode,omitempty"`
	DryRun          *bool   `json:"dryRun,omitempty"`
	InPrivate       *bool   `json:"inPrivate,omitempty"`
	LoginUrl        *string `json:"loginUrl,omitempty"`
	PageLoadSeconds *int32  `json:"pageLoadSeconds,omitempty"`
}

// MicrosoftDeviceLoginResult defines model for MicrosoftDeviceLoginResult.
type MicrosoftDeviceLoginResult struct {
	Actions        []string  `json:"actions"`
	CompletedAtUtc time.Time `json:"completedAtUtc"`
	Errors         []string  `json:"errors"`
	InPrivate      bool      `json:"inPrivate"`
	LoginUrl       string    `json:"loginUrl"`
	Success        bool      `json:"success"`
}

// OperatorError defines model for OperatorError.
type OperatorError struct {
	Code        *string            `json:"code,omitempty"`
	Details     *map[string]string `json:"details"`
	Message     *string            `json:"message,omitempty"`
	Remediation *string            `json:"remediation,omitempty"`
}

// PowerPointEditAssert defines model for PowerPointEditAssert.
type PowerPointEditAssert struct {
	AllowMultiple    bool `json:"allowMultiple"`
	ExactlyOneTarget bool `json:"exactlyOneTarget"`
}

// PowerPointEditOperation defines model for PowerPointEditOperation.
type PowerPointEditOperation struct {
	Assert     *PowerPointEditAssert `json:"assert"`
	Column     *int32                `json:"column"`
	FillColor  *string               `json:"fillColor"`
	Find       *string               `json:"find"`
	Fit        *string               `json:"fit"`
	Id         string                `json:"id"`
	ImagePath  *string               `json:"imagePath"`
	Op         string                `json:"op"`
	OutputPath *string               `json:"outputPath"`
	Row        *int32                `json:"row"`
	Target     *PowerPointEditTarget `json:"target"`
	Value      *string               `json:"value"`
	Visible    *bool                 `json:"visible"`
}

// PowerPointEditOutcome defines model for PowerPointEditOutcome.
type PowerPointEditOutcome struct {
	After    *string  `json:"after"`
	Before   *string  `json:"before"`
	Changed  int32    `json:"changed"`
	Errors   []string `json:"errors"`
	Id       string   `json:"id"`
	Matched  int32    `json:"matched"`
	Op       string   `json:"op"`
	Warnings []string `json:"warnings"`
}

// PowerPointEditRequest defines model for PowerPointEditRequest.
type PowerPointEditRequest struct {
	AllowMacroEnabled *bool                      `json:"allowMacroEnabled,omitempty"`
	DryRun            *bool                      `json:"dryRun,omitempty"`
	Edits             *[]PowerPointEditOperation `json:"edits,omitempty"`
	ExchangePath      *string                    `json:"exchangePath"`
	Mode              *string                    `json:"mode,omitempty"`
	OutputPath        *string                    `json:"outputPath"`
	PresentationPath  *string                    `json:"presentationPath"`
	PresentationUrl   *string                    `json:"presentationUrl"`
	SaveMode          *string                    `json:"saveMode,omitempty"`
}

// PowerPointEditResult defines model for PowerPointEditResult.
type PowerPointEditResult struct {
	CompletedAtUtc   time.Time               `json:"completedAtUtc"`
	DryRun           bool                    `json:"dryRun"`
	Edits            []PowerPointEditOutcome `json:"edits"`
	Errors           []string                `json:"errors"`
	JobId            string                  `json:"jobId"`
	OutputPath       *string                 `json:"outputPath"`
	PresentationPath *string                 `json:"presentationPath"`
	Success          bool                    `json:"success"`
	Warnings         []string                `json:"warnings"`
}

// PowerPointEditTarget defines model for PowerPointEditTarget.
type PowerPointEditTarget struct {
	Shape *PowerPointShapeSelector `json:"shape"`
	Slide *PowerPointSlideSelector `json:"slide"`
}

// PowerPointInspectRequest defines model for PowerPointInspectRequest.
type PowerPointInspectRequest struct {
	ExchangePath     *string `json:"exchangePath"`
	IncludeHidden    *bool   `json:"includeHidden,omitempty"`
	IncludeText      *bool   `json:"includeText,omitempty"`
	PresentationPath *string `json:"presentationPath"`
	PresentationUrl  *string `json:"presentationUrl"`
}

// PowerPointInspectResult defines model for PowerPointInspectResult.
type PowerPointInspectResult struct {
	CompletedAtUtc time.Time                  `json:"completedAtUtc"`
	Errors         []string                   `json:"errors"`
	Presentation   *PowerPointPresentationRef `json:"presentation"`
	Slides         []PowerPointSlideRef       `json:"slides"`
	Success        bool                       `json:"success"`
	Warnings       []string                   `json:"warnings"`
}

// PowerPointPresentationRef defines model for PowerPointPresentationRef.
type PowerPointPresentationRef struct {
	Name       string  `json:"name"`
	Path       *string `json:"path"`
	SlideCount int32   `json:"slideCount"`
}

// PowerPointShapeRef defines model for PowerPointShapeRef.
type PowerPointShapeRef struct {
	AltText    *string           `json:"altText"`
	HasChart   bool              `json:"hasChart"`
	HasTable   bool              `json:"hasTable"`
	HasText    bool              `json:"hasText"`
	Id         int32             `json:"id"`
	Level      int32             `json:"level"`
	Name       string            `json:"name"`
	ParentName *string           `json:"parentName"`
	Tags       map[string]string `json:"tags"`
	Text       *string           `json:"text"`
	Type       string            `json:"type"`
	Visible    bool              `json:"visible"`
}

// PowerPointShapeSelector defines model for PowerPointShapeSelector.
type PowerPointShapeSelector struct {
	AltText      *string            `json:"altText"`
	Id           *int32             `json:"id"`
	Name         *string            `json:"name"`
	Tag          *map[string]string `json:"tag"`
	TextContains *string            `json:"textContains"`
}

// PowerPointSlideRef defines model for PowerPointSlideRef.
type PowerPointSlideRef struct {
	Index   int32                `json:"index"`
	Shapes  []PowerPointShapeRef `json:"shapes"`
	SlideId int32                `json:"slideId"`
	Tags    map[string]string    `json:"tags"`
	Title   *string              `json:"title"`
}

// PowerPointSlideSelector defines model for PowerPointSlideSelector.
type PowerPointSlideSelector struct {
	Index   *int32             `json:"index"`
	SlideId *int32             `json:"slideId"`
	Tag     *map[string]string `json:"tag"`
	Title   *string            `json:"title"`
}

// ScreenshotFormat defines model for ScreenshotFormat.
type ScreenshotFormat string

// ScreenshotResult defines model for ScreenshotResult.
type ScreenshotResult struct {
	Backend       string       `json:"backend"`
	CapturedAtUtc time.Time    `json:"capturedAtUtc"`
	DpiScale      float64      `json:"dpiScale"`
	ImageBase64   string       `json:"imageBase64"`
	JpegQuality   *int32       `json:"jpegQuality"`
	LongestEdge   int32        `json:"longestEdge"`
	Lossless      bool         `json:"lossless"`
	MediaType     string       `json:"mediaType"`
	NativeBounds  WindowBounds `json:"nativeBounds"`
	PixelHeight   int32        `json:"pixelHeight"`
	PixelWidth    int32        `json:"pixelWidth"`
}

// UInt32 defines model for UInt32.
type UInt32 = map[string]interface{}

// UiElementRef defines model for UiElementRef.
type UiElementRef struct {
	AutomationId string       `json:"automationId"`
	Bounds       WindowBounds `json:"bounds"`
	ControlType  string       `json:"controlType"`
	IsEnabled    bool         `json:"isEnabled"`
	IsOffscreen  bool         `json:"isOffscreen"`
	Name         string       `json:"name"`
	RuntimeId    string       `json:"runtimeId"`
}

// UiQuery defines model for UiQuery.
type UiQuery struct {
	AutomationId     *string `json:"automationId"`
	ControlType      *string `json:"controlType"`
	IncludeOffscreen bool    `json:"includeOffscreen"`
	MaxResults       int32   `json:"maxResults"`
	Name             *string `json:"name"`
	WindowHwnd       *int64  `json:"windowHwnd"`
}

// UiaClickRequest defines model for UiaClickRequest.
type UiaClickRequest struct {
	DoubleClick *bool    `json:"doubleClick,omitempty"`
	Query       *UiQuery `json:"query,omitempty"`
}

// UiaTypeRequest defines model for UiaTypeRequest.
type UiaTypeRequest struct {
	Append *bool    `json:"append,omitempty"`
	Query  *UiQuery `json:"query,omitempty"`
	Submit *bool    `json:"submit,omitempty"`
	Text   *string  `json:"text,omitempty"`
}

// WindowBounds defines model for WindowBounds.
type WindowBounds struct {
	Height int32 `json:"height"`
	Width  int32 `json:"width"`
	X      int32 `json:"x"`
	Y      int32 `json:"y"`
}

// WindowRef defines model for WindowRef.
type WindowRef struct {
	Bounds        WindowBounds `json:"bounds"`
	CapturedAtUtc time.Time    `json:"capturedAtUtc"`
	ClassName     string       `json:"className"`
	DpiScale      float64      `json:"dpiScale"`
	Hwnd          int64        `json:"hwnd"`
	IsForeground  bool         `json:"isForeground"`
	IsMinimized   bool         `json:"isMinimized"`
	ProcessId     UInt32       `json:"processId"`
	Title         string       `json:"title"`
}

// CaptureWindowParams defines parameters for CaptureWindow.
type CaptureWindowParams struct {
	Format *ScreenshotFormat `form:"format,omitempty" json:"format,omitempty"`
}

// StartMicrosoftDeviceLoginJSONRequestBody defines body for StartMicrosoftDeviceLogin for application/json ContentType.
type StartMicrosoftDeviceLoginJSONRequestBody = MicrosoftDeviceLoginRequest

// SendHotkeyJSONRequestBody defines body for SendHotkey for application/json ContentType.
type SendHotkeyJSONRequestBody = HotkeyRequest

// DownloadMailAttachmentsJSONRequestBody defines body for DownloadMailAttachments for application/json ContentType.
type DownloadMailAttachmentsJSONRequestBody = MailDownloadRequest

// ListMailFoldersJSONRequestBody defines body for ListMailFolders for application/json ContentType.
type ListMailFoldersJSONRequestBody = MailListFoldersRequest

// SearchMailMessagesJSONRequestBody defines body for SearchMailMessages for application/json ContentType.
type SearchMailMessagesJSONRequestBody = MailSearchRequest

// EditPowerPointJSONRequestBody defines body for EditPowerPoint for application/json ContentType.
type EditPowerPointJSONRequestBody = PowerPointEditRequest

// InspectPowerPointJSONRequestBody defines body for InspectPowerPoint for application/json ContentType.
type InspectPowerPointJSONRequestBody = PowerPointInspectRequest

// ClickUiJSONRequestBody defines body for ClickUi for application/json ContentType.
type ClickUiJSONRequestBody = UiaClickRequest

// QueryUiJSONRequestBody defines body for QueryUi for application/json ContentType.
type QueryUiJSONRequestBody = UiQuery

// TypeUiJSONRequestBody defines body for TypeUi for application/json ContentType.
type TypeUiJSONRequestBody = UiaTypeRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// StartMicrosoftDeviceLoginWithBody request with any body
	StartMicrosoftDeviceLoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	StartMicrosoftDeviceLogin(ctx context.Context, body StartMicrosoftDeviceLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SendHotkeyWithBody request with any body
	SendHotkeyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SendHotkey(ctx context.Context, body SendHotkeyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DownloadMailAttachmentsWithBody request with any body
	DownloadMailAttachmentsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	DownloadMailAttachments(ctx context.Context, body DownloadMailAttachmentsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListMailFoldersWithBody request with any body
	ListMailFoldersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ListMailFolders(ctx context.Context, body ListMailFoldersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SearchMailMessagesWithBody request with any body
	SearchMailMessagesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SearchMailMessages(ctx context.Context, body SearchMailMessagesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMailRun request
	GetMailRun(ctx context.Context, runId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMailStatus request
	GetMailStatus(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// EditPowerPointWithBody request with any body
	EditPowerPointWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	EditPowerPoint(ctx context.Context, body EditPowerPointJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// InspectPowerPointWithBody request with any body
	InspectPowerPointWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	InspectPowerPoint(ctx context.Context, body InspectPowerPointJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPowerPointJob request
	GetPowerPointJob(ctx context.Context, jobId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ClickUiWithBody request with any body
	ClickUiWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ClickUi(ctx context.Context, body ClickUiJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// QueryUiWithBody request with any body
	QueryUiWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	QueryUi(ctx context.Context, body QueryUiJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TypeUiWithBody request with any body
	TypeUiWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	TypeUi(ctx context.Context, body TypeUiJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListWindows request
	ListWindows(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ActivateWindow request
	ActivateWindow(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CaptureWindow request
	CaptureWindow(ctx context.Context, id int64, params *CaptureWindowParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) StartMicrosoftDeviceLoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStartMicrosoftDeviceLoginRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StartMicrosoftDeviceLogin(ctx context.Context, body StartMicrosoftDeviceLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStartMicrosoftDeviceLoginRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SendHotkeyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSendHotkeyRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SendHotkey(ctx context.Context, body SendHotkeyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSendHotkeyRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DownloadMailAttachmentsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDownloadMailAttachmentsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DownloadMailAttachments(ctx context.Context, body DownloadMailAttachmentsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDownloadMailAttachmentsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListMailFoldersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListMailFoldersRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListMailFolders(ctx context.Context, body ListMailFoldersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListMailFoldersRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SearchMailMessagesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSearchMailMessagesRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SearchMailMessages(ctx context.Context, body SearchMailMessagesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSearchMailMessagesRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetMailRun(ctx context.Context, runId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMailRunRequest(c.Server, runId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetMailStatus(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMailStatusRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) EditPowerPointWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewEditPowerPointRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) EditPowerPoint(ctx context.Context, body EditPowerPointJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewEditPowerPointRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InspectPowerPointWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInspectPowerPointRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InspectPowerPoint(ctx context.Context, body InspectPowerPointJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInspectPowerPointRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPowerPointJob(ctx context.Context, jobId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPowerPointJobRequest(c.Server, jobId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ClickUiWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewClickUiRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ClickUi(ctx context.Context, body ClickUiJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewClickUiRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) QueryUiWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewQueryUiRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) QueryUi(ctx context.Context, body QueryUiJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewQueryUiRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TypeUiWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTypeUiRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TypeUi(ctx context.Context, body TypeUiJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTypeUiRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListWindows(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListWindowsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ActivateWindow(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewActivateWindowRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CaptureWindow(ctx context.Context, id int64, params *CaptureWindowParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCaptureWindowRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewStartMicrosoftDeviceLoginRequest calls the generic StartMicrosoftDeviceLogin builder with application/json body
func NewStartMicrosoftDeviceLoginRequest(server string, body StartMicrosoftDeviceLoginJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewStartMicrosoftDeviceLoginRequestWithBody(server, "application/json", bodyReader)
}

// NewStartMicrosoftDeviceLoginRequestWithBody generates requests for StartMicrosoftDeviceLogin with any type of body
func NewStartMicrosoftDeviceLoginRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/auth/microsoft/device-login")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSendHotkeyRequest calls the generic SendHotkey builder with application/json body
func NewSendHotkeyRequest(server string, body SendHotkeyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSendHotkeyRequestWithBody(server, "application/json", bodyReader)
}

// NewSendHotkeyRequestWithBody generates requests for SendHotkey with any type of body
func NewSendHotkeyRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/input/hotkey")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDownloadMailAttachmentsRequest calls the generic DownloadMailAttachments builder with application/json body
func NewDownloadMailAttachmentsRequest(server string, body DownloadMailAttachmentsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewDownloadMailAttachmentsRequestWithBody(server, "application/json", bodyReader)
}

// NewDownloadMailAttachmentsRequestWithBody generates requests for DownloadMailAttachments with any type of body
func NewDownloadMailAttachmentsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/mail/attachments/download")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListMailFoldersRequest calls the generic ListMailFolders builder with application/json body
func NewListMailFoldersRequest(server string, body ListMailFoldersJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewListMailFoldersRequestWithBody(server, "application/json", bodyReader)
}

// NewListMailFoldersRequestWithBody generates requests for ListMailFolders with any type of body
func NewListMailFoldersRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/mail/folders")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewSearchMailMessagesRequest calls the generic SearchMailMessages builder with application/json body
func NewSearchMailMessagesRequest(server string, body SearchMailMessagesJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSearchMailMessagesRequestWithBody(server, "application/json", bodyReader)
}

// NewSearchMailMessagesRequestWithBody generates requests for SearchMailMessages with any type of body
func NewSearchMailMessagesRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/mail/messages/search")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetMailRunRequest generates requests for GetMailRun
func NewGetMailRunRequest(server string, runId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "runId", runtime.ParamLocationPath, runId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/mail/runs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetMailStatusRequest generates requests for GetMailStatus
func NewGetMailStatusRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/mail/status")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewEditPowerPointRequest calls the generic EditPowerPoint builder with application/json body
func NewEditPowerPointRequest(server string, body EditPowerPointJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewEditPowerPointRequestWithBody(server, "application/json", bodyReader)
}

// NewEditPowerPointRequestWithBody generates requests for EditPowerPoint with any type of body
func NewEditPowerPointRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/powerpoint/edit")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewInspectPowerPointRequest calls the generic InspectPowerPoint builder with application/json body
func NewInspectPowerPointRequest(server string, body InspectPowerPointJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewInspectPowerPointRequestWithBody(server, "application/json", bodyReader)
}

// NewInspectPowerPointRequestWithBody generates requests for InspectPowerPoint with any type of body
func NewInspectPowerPointRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/powerpoint/inspect")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetPowerPointJobRequest generates requests for GetPowerPointJob
func NewGetPowerPointJobRequest(server string, jobId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "jobId", runtime.ParamLocationPath, jobId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/powerpoint/jobs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewClickUiRequest calls the generic ClickUi builder with application/json body
func NewClickUiRequest(server string, body ClickUiJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewClickUiRequestWithBody(server, "application/json", bodyReader)
}

// NewClickUiRequestWithBody generates requests for ClickUi with any type of body
func NewClickUiRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/uia/click")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewQueryUiRequest calls the generic QueryUi builder with application/json body
func NewQueryUiRequest(server string, body QueryUiJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewQueryUiRequestWithBody(server, "application/json", bodyReader)
}

// NewQueryUiRequestWithBody generates requests for QueryUi with any type of body
func NewQueryUiRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/uia/query")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewTypeUiRequest calls the generic TypeUi builder with application/json body
func NewTypeUiRequest(server string, body TypeUiJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewTypeUiRequestWithBody(server, "application/json", bodyReader)
}

// NewTypeUiRequestWithBody generates requests for TypeUi with any type of body
func NewTypeUiRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/uia/type")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListWindowsRequest generates requests for ListWindows
func NewListWindowsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/windows")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewActivateWindowRequest generates requests for ActivateWindow
func NewActivateWindowRequest(server string, id int64) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/windows/%s/activate", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCaptureWindowRequest generates requests for CaptureWindow
func NewCaptureWindowRequest(server string, id int64, params *CaptureWindowParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/windows/%s/screenshot", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Format != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "format", runtime.ParamLocationQuery, *params.Format); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// StartMicrosoftDeviceLoginWithBodyWithResponse request with any body
	StartMicrosoftDeviceLoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*StartMicrosoftDeviceLoginResponse, error)

	StartMicrosoftDeviceLoginWithResponse(ctx context.Context, body StartMicrosoftDeviceLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*StartMicrosoftDeviceLoginResponse, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)

	// SendHotkeyWithBodyWithResponse request with any body
	SendHotkeyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SendHotkeyResponse, error)

	SendHotkeyWithResponse(ctx context.Context, body SendHotkeyJSONRequestBody, reqEditors ...RequestEditorFn) (*SendHotkeyResponse, error)

	// DownloadMailAttachmentsWithBodyWithResponse request with any body
	DownloadMailAttachmentsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DownloadMailAttachmentsResponse, error)

	DownloadMailAttachmentsWithResponse(ctx context.Context, body DownloadMailAttachmentsJSONRequestBody, reqEditors ...RequestEditorFn) (*DownloadMailAttachmentsResponse, error)

	// ListMailFoldersWithBodyWithResponse request with any body
	ListMailFoldersWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ListMailFoldersResponse, error)

	ListMailFoldersWithResponse(ctx context.Context, body ListMailFoldersJSONRequestBody, reqEditors ...RequestEditorFn) (*ListMailFoldersResponse, error)

	// SearchMailMessagesWithBodyWithResponse request with any body
	SearchMailMessagesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SearchMailMessagesResponse, error)

	SearchMailMessagesWithResponse(ctx context.Context, body SearchMailMessagesJSONRequestBody, reqEditors ...RequestEditorFn) (*SearchMailMessagesResponse, error)

	// GetMailRunWithResponse request
	GetMailRunWithResponse(ctx context.Context, runId string, reqEditors ...RequestEditorFn) (*GetMailRunResponse, error)

	// GetMailStatusWithResponse request
	GetMailStatusWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetMailStatusResponse, error)

	// EditPowerPointWithBodyWithResponse request with any body
	EditPowerPointWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*EditPowerPointResponse, error)

	EditPowerPointWithResponse(ctx context.Context, body EditPowerPointJSONRequestBody, reqEditors ...RequestEditorFn) (*EditPowerPointResponse, error)

	// InspectPowerPointWithBodyWithResponse request with any body
	InspectPowerPointWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InspectPowerPointResponse, error)

	InspectPowerPointWithResponse(ctx context.Context, body InspectPowerPointJSONRequestBody, reqEditors ...RequestEditorFn) (*InspectPowerPointResponse, error)

	// GetPowerPointJobWithResponse request
	GetPowerPointJobWithResponse(ctx context.Context, jobId string, reqEditors ...RequestEditorFn) (*GetPowerPointJobResponse, error)

	// ClickUiWithBodyWithResponse request with any body
	ClickUiWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ClickUiResponse, error)

	ClickUiWithResponse(ctx context.Context, body ClickUiJSONRequestBody, reqEditors ...RequestEditorFn) (*ClickUiResponse, error)

	// QueryUiWithBodyWithResponse request with any body
	QueryUiWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*QueryUiResponse, error)

	QueryUiWithResponse(ctx context.Context, body QueryUiJSONRequestBody, reqEditors ...RequestEditorFn) (*QueryUiResponse, error)

	// TypeUiWithBodyWithResponse request with any body
	TypeUiWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TypeUiResponse, error)

	TypeUiWithResponse(ctx context.Context, body TypeUiJSONRequestBody, reqEditors ...RequestEditorFn) (*TypeUiResponse, error)

	// ListWindowsWithResponse request
	ListWindowsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListWindowsResponse, error)

	// ActivateWindowWithResponse request
	ActivateWindowWithResponse(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*ActivateWindowResponse, error)

	// CaptureWindowWithResponse request
	CaptureWindowWithResponse(ctx context.Context, id int64, params *CaptureWindowParams, reqEditors ...RequestEditorFn) (*CaptureWindowResponse, error)
}

type StartMicrosoftDeviceLoginResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MicrosoftDeviceLoginResult
	JSON4XX      *OperatorError
	JSON5XX      *OperatorError
}

// Status returns HTTPResponse.Status
func (r StartMicrosoftDeviceLoginResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StartMicrosoftDeviceLoginResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResult
	JSON4XX      *OperatorError
	JSON5XX      *OperatorError
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SendHotkeyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ActionResult
	JSON4XX      *OperatorError
	JSON5XX      *OperatorError
}

// Status returns HTTPResponse.Status
func (r SendHotkeyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SendHotkeyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DownloadMailAttachmentsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MailDownloadResult
	JSON4XX      *OperatorError
	JSON5XX      *OperatorError
}

// Status returns HTTPResponse.Status
func (r DownloadMailAttachmentsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DownloadMailAttachmentsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListMailFoldersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MailFoldersResult
	JSON4XX      *OperatorError
	JSON5XX      *OperatorError
}

// Status returns HTTPResponse.Status
func (r ListMailFoldersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListMailFoldersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SearchMailMessagesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MailSearchResult
	JSON4XX      *OperatorError
	JSON5XX      *OperatorError
}

// Status returns HTTPResponse.Status
func (r SearchMailMessagesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SearchMailMessagesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetMailRunResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MailDownloadResult
	JSON4XX      *OperatorError
	JSON5XX      *OperatorError
}

// Status returns HTTPResponse.Status
func (r GetMailRunResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMailRunResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetMailStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MailStatusResult
	JSON4XX      *OperatorError
	JSON5XX      *OperatorError
}

// Status returns HTTPResponse.Status
func (r GetMailStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMailStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type EditPowerPointResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PowerPointEditResult
	JSON4XX      *OperatorError
	JSON5XX      *OperatorError
}

// Status returns HTTPResponse.Status
func (r EditPowerPointResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r EditPowerPointResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type InspectPowerPointResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PowerPointInspectResult
	JSON4XX      *OperatorError
	JSON5XX      *OperatorError
}

// Status returns HTTPResponse.Status
func (r InspectPowerPointResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r InspectPowerPointResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPowerPointJobResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PowerPointEditResult
	JSON4XX      *OperatorError
	JSON5XX      *OperatorError
}

// Status returns HTTPResponse.Status
func (r GetPowerPointJobResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPowerPointJobResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ClickUiResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ActionResult
	JSON4XX      *OperatorError
	JSON5XX      *OperatorError
}

// Status returns HTTPResponse.Status
func (r ClickUiResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ClickUiResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type QueryUiResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]UiElementRef
	JSON4XX      *OperatorError
	JSON5XX      *OperatorError
}

// Status returns HTTPResponse.Status
func (r QueryUiResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r QueryUiResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TypeUiResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ActionResult
	JSON4XX      *OperatorError
	JSON5XX      *OperatorError
}

// Status returns HTTPResponse.Status
func (r TypeUiResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TypeUiResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListWindowsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]WindowRef
	JSON4XX      *OperatorError
	JSON5XX      *OperatorError
}

// Status returns HTTPResponse.Status
func (r ListWindowsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListWindowsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ActivateWindowResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ActionResult
	JSON4XX      *OperatorError
	JSON5XX      *OperatorError
}

// Status returns HTTPResponse.Status
func (r ActivateWindowResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ActivateWindowResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CaptureWindowResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ScreenshotResult
	JSON4XX      *OperatorError
	JSON5XX      *OperatorError
}

// Status returns HTTPResponse.Status
func (r CaptureWindowResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CaptureWindowResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// StartMicrosoftDeviceLoginWithBodyWithResponse request with arbitrary body returning *StartMicrosoftDeviceLoginResponse
func (c *ClientWithResponses) StartMicrosoftDeviceLoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*StartMicrosoftDeviceLoginResponse, error) {
	rsp, err := c.StartMicrosoftDeviceLoginWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStartMicrosoftDeviceLoginResponse(rsp)
}

func (c *ClientWithResponses) StartMicrosoftDeviceLoginWithResponse(ctx context.Context, body StartMicrosoftDeviceLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*StartMicrosoftDeviceLoginResponse, error) {
	rsp, err := c.StartMicrosoftDeviceLogin(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStartMicrosoftDeviceLoginResponse(rsp)
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// SendHotkeyWithBodyWithResponse request with arbitrary body returning *SendHotkeyResponse
func (c *ClientWithResponses) SendHotkeyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SendHotkeyResponse, error) {
	rsp, err := c.SendHotkeyWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSendHotkeyResponse(rsp)
}

func (c *ClientWithResponses) SendHotkeyWithResponse(ctx context.Context, body SendHotkeyJSONRequestBody, reqEditors ...RequestEditorFn) (*SendHotkeyResponse, error) {
	rsp, err := c.SendHotkey(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSendHotkeyResponse(rsp)
}

// DownloadMailAttachmentsWithBodyWithResponse request with arbitrary body returning *DownloadMailAttachmentsResponse
func (c *ClientWithResponses) DownloadMailAttachmentsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DownloadMailAttachmentsResponse, error) {
	rsp, err := c.DownloadMailAttachmentsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDownloadMailAttachmentsResponse(rsp)
}

func (c *ClientWithResponses) DownloadMailAttachmentsWithResponse(ctx context.Context, body DownloadMailAttachmentsJSONRequestBody, reqEditors ...RequestEditorFn) (*DownloadMailAttachmentsResponse, error) {
	rsp, err := c.DownloadMailAttachments(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDownloadMailAttachmentsResponse(rsp)
}

// ListMailFoldersWithBodyWithResponse request with arbitrary body returning *ListMailFoldersResponse
func (c *ClientWithResponses) ListMailFoldersWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ListMailFoldersResponse, error) {
	rsp, err := c.ListMailFoldersWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListMailFoldersResponse(rsp)
}

func (c *ClientWithResponses) ListMailFoldersWithResponse(ctx context.Context, body ListMailFoldersJSONRequestBody, reqEditors ...RequestEditorFn) (*ListMailFoldersResponse, error) {
	rsp, err := c.ListMailFolders(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListMailFoldersResponse(rsp)
}

// SearchMailMessagesWithBodyWithResponse request with arbitrary body returning *SearchMailMessagesResponse
func (c *ClientWithResponses) SearchMailMessagesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SearchMailMessagesResponse, error) {
	rsp, err := c.SearchMailMessagesWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSearchMailMessagesResponse(rsp)
}

func (c *ClientWithResponses) SearchMailMessagesWithResponse(ctx context.Context, body SearchMailMessagesJSONRequestBody, reqEditors ...RequestEditorFn) (*SearchMailMessagesResponse, error) {
	rsp, err := c.SearchMailMessages(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSearchMailMessagesResponse(rsp)
}

// GetMailRunWithResponse request returning *GetMailRunResponse
func (c *ClientWithResponses) GetMailRunWithResponse(ctx context.Context, runId string, reqEditors ...RequestEditorFn) (*GetMailRunResponse, error) {
	rsp, err := c.GetMailRun(ctx, runId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMailRunResponse(rsp)
}

// GetMailStatusWithResponse request returning *GetMailStatusResponse
func (c *ClientWithResponses) GetMailStatusWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetMailStatusResponse, error) {
	rsp, err := c.GetMailStatus(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMailStatusResponse(rsp)
}

// EditPowerPointWithBodyWithResponse request with arbitrary body returning *EditPowerPointResponse
func (c *ClientWithResponses) EditPowerPointWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*EditPowerPointResponse, error) {
	rsp, err := c.EditPowerPointWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseEditPowerPointResponse(rsp)
}

func (c *ClientWithResponses) EditPowerPointWithResponse(ctx context.Context, body EditPowerPointJSONRequestBody, reqEditors ...RequestEditorFn) (*EditPowerPointResponse, error) {
	rsp, err := c.EditPowerPoint(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseEditPowerPointResponse(rsp)
}

// InspectPowerPointWithBodyWithResponse request with arbitrary body returning *InspectPowerPointResponse
func (c *ClientWithResponses) InspectPowerPointWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InspectPowerPointResponse, error) {
	rsp, err := c.InspectPowerPointWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInspectPowerPointResponse(rsp)
}

func (c *ClientWithResponses) InspectPowerPointWithResponse(ctx context.Context, body InspectPowerPointJSONRequestBody, reqEditors ...RequestEditorFn) (*InspectPowerPointResponse, error) {
	rsp, err := c.InspectPowerPoint(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInspectPowerPointResponse(rsp)
}

// GetPowerPointJobWithResponse request returning *GetPowerPointJobResponse
func (c *ClientWithResponses) GetPowerPointJobWithResponse(ctx context.Context, jobId string, reqEditors ...RequestEditorFn) (*GetPowerPointJobResponse, error) {
	rsp, err := c.GetPowerPointJob(ctx, jobId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPowerPointJobResponse(rsp)
}

// ClickUiWithBodyWithResponse request with arbitrary body returning *ClickUiResponse
func (c *ClientWithResponses) ClickUiWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ClickUiResponse, error) {
	rsp, err := c.ClickUiWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseClickUiResponse(rsp)
}

func (c *ClientWithResponses) ClickUiWithResponse(ctx context.Context, body ClickUiJSONRequestBody, reqEditors ...RequestEditorFn) (*ClickUiResponse, error) {
	rsp, err := c.ClickUi(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseClickUiResponse(rsp)
}

// QueryUiWithBodyWithResponse request with arbitrary body returning *QueryUiResponse
func (c *ClientWithResponses) QueryUiWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*QueryUiResponse, error) {
	rsp, err := c.QueryUiWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseQueryUiResponse(rsp)
}

func (c *ClientWithResponses) QueryUiWithResponse(ctx context.Context, body QueryUiJSONRequestBody, reqEditors ...RequestEditorFn) (*QueryUiResponse, error) {
	rsp, err := c.QueryUi(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseQueryUiResponse(rsp)
}

// TypeUiWithBodyWithResponse request with arbitrary body returning *TypeUiResponse
func (c *ClientWithResponses) TypeUiWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TypeUiResponse, error) {
	rsp, err := c.TypeUiWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTypeUiResponse(rsp)
}

func (c *ClientWithResponses) TypeUiWithResponse(ctx context.Context, body TypeUiJSONRequestBody, reqEditors ...RequestEditorFn) (*TypeUiResponse, error) {
	rsp, err := c.TypeUi(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTypeUiResponse(rsp)
}

// ListWindowsWithResponse request returning *ListWindowsResponse
func (c *ClientWithResponses) ListWindowsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListWindowsResponse, error) {
	rsp, err := c.ListWindows(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListWindowsResponse(rsp)
}

// ActivateWindowWithResponse request returning *ActivateWindowResponse
func (c *ClientWithResponses) ActivateWindowWithResponse(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*ActivateWindowResponse, error) {
	rsp, err := c.ActivateWindow(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseActivateWindowResponse(rsp)
}

// CaptureWindowWithResponse request returning *CaptureWindowResponse
func (c *ClientWithResponses) CaptureWindowWithResponse(ctx context.Context, id int64, params *CaptureWindowParams, reqEditors ...RequestEditorFn) (*CaptureWindowResponse, error) {
	rsp, err := c.CaptureWindow(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCaptureWindowResponse(rsp)
}

// ParseStartMicrosoftDeviceLoginResponse parses an HTTP response from a StartMicrosoftDeviceLoginWithResponse call
func ParseStartMicrosoftDeviceLoginResponse(rsp *http.Response) (*StartMicrosoftDeviceLoginResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StartMicrosoftDeviceLoginResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MicrosoftDeviceLoginResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseSendHotkeyResponse parses an HTTP response from a SendHotkeyWithResponse call
func ParseSendHotkeyResponse(rsp *http.Response) (*SendHotkeyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SendHotkeyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ActionResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseDownloadMailAttachmentsResponse parses an HTTP response from a DownloadMailAttachmentsWithResponse call
func ParseDownloadMailAttachmentsResponse(rsp *http.Response) (*DownloadMailAttachmentsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DownloadMailAttachmentsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MailDownloadResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseListMailFoldersResponse parses an HTTP response from a ListMailFoldersWithResponse call
func ParseListMailFoldersResponse(rsp *http.Response) (*ListMailFoldersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListMailFoldersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MailFoldersResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseSearchMailMessagesResponse parses an HTTP response from a SearchMailMessagesWithResponse call
func ParseSearchMailMessagesResponse(rsp *http.Response) (*SearchMailMessagesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SearchMailMessagesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MailSearchResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseGetMailRunResponse parses an HTTP response from a GetMailRunWithResponse call
func ParseGetMailRunResponse(rsp *http.Response) (*GetMailRunResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMailRunResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MailDownloadResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseGetMailStatusResponse parses an HTTP response from a GetMailStatusWithResponse call
func ParseGetMailStatusResponse(rsp *http.Response) (*GetMailStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMailStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MailStatusResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseEditPowerPointResponse parses an HTTP response from a EditPowerPointWithResponse call
func ParseEditPowerPointResponse(rsp *http.Response) (*EditPowerPointResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &EditPowerPointResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PowerPointEditResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseInspectPowerPointResponse parses an HTTP response from a InspectPowerPointWithResponse call
func ParseInspectPowerPointResponse(rsp *http.Response) (*InspectPowerPointResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &InspectPowerPointResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PowerPointInspectResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseGetPowerPointJobResponse parses an HTTP response from a GetPowerPointJobWithResponse call
func ParseGetPowerPointJobResponse(rsp *http.Response) (*GetPowerPointJobResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPowerPointJobResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PowerPointEditResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseClickUiResponse parses an HTTP response from a ClickUiWithResponse call
func ParseClickUiResponse(rsp *http.Response) (*ClickUiResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ClickUiResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ActionResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseQueryUiResponse parses an HTTP response from a QueryUiWithResponse call
func ParseQueryUiResponse(rsp *http.Response) (*QueryUiResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &QueryUiResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []UiElementRef
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseTypeUiResponse parses an HTTP response from a TypeUiWithResponse call
func ParseTypeUiResponse(rsp *http.Response) (*TypeUiResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TypeUiResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ActionResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseListWindowsResponse parses an HTTP response from a ListWindowsWithResponse call
func ParseListWindowsResponse(rsp *http.Response) (*ListWindowsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListWindowsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []WindowRef
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseActivateWindowResponse parses an HTTP response from a ActivateWindowWithResponse call
func ParseActivateWindowResponse(rsp *http.Response) (*ActivateWindowResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ActivateWindowResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ActionResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}

// ParseCaptureWindowResponse parses an HTTP response from a CaptureWindowWithResponse call
func ParseCaptureWindowResponse(rsp *http.Response) (*CaptureWindowResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CaptureWindowResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ScreenshotResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 5:
		var dest OperatorError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON5XX = &dest

	}

	return response, nil
}
