namespace WindowsOperator.Core;

public static class ErrorCodes
{
    public const string InvalidRequest = "invalid_request";
    public const string RouteNotFound = "route_not_found";
    public const string MethodNotAllowed = "method_not_allowed";
    public const string InternalError = "internal_error";
    public const string LockedDesktop = "locked_desktop";
    public const string UipiBlocked = "uipi_blocked";
    public const string ElevatedTarget = "elevated_target";
    public const string WindowNotFound = "window_not_found";
    public const string BlankCapture = "blank_capture";
    public const string MinimizedRdp = "minimized_rdp";
    public const string UnsupportedControl = "unsupported_control";
    public const string AuthUnavailable = "auth_unavailable";
    public const string AuthRunNotFound = "auth_run_not_found";
    public const string BrowserSessionNotFound = "browser_session_not_found";
    public const string WorkbenchSessionNotFound = "workbench_session_not_found";
    public const string PowerPointUnavailable = "powerpoint_unavailable";
    public const string PowerPointValidationFailed = "powerpoint_validation_failed";
    public const string PowerPointSessionNotFound = "powerpoint_session_not_found";
    public const string PowerPointJobNotFound = "powerpoint_job_not_found";
    public const string ArtifactNotFound = "artifact_not_found";
    public const string DevAutomationDisabled = "dev_automation_disabled";
    public const string DevRawJsDisabled = "dev_raw_js_disabled";
    public const string DevAutomationValidationFailed = "dev_automation_validation_failed";
    public const string MailUnavailable = "mail_unavailable";
    public const string MailFolderNotFound = "mail_folder_not_found";
    public const string MailRunNotFound = "mail_run_not_found";
    public const string PowerAutomateMcpUnavailable = "power_automate_mcp_unavailable";
    public const string PowerAutomateMcpValidationFailed = "power_automate_mcp_validation_failed";
    public const string OpenApiNamespaceNotFound = "openapi_namespace_not_found";
    public const string OpenApiSurfaceInvalid = "openapi_surface_invalid";
    public const string OneDriveUnavailable = "onedrive_unavailable";
    public const string OneDriveRootNotFound = "onedrive_root_not_found";
    public const string OneDriveFileNotFound = "onedrive_file_not_found";
    public const string OneDriveLeaseNotFound = "onedrive_lease_not_found";
    public const string OneDriveReclaimNotFound = "onedrive_reclaim_not_found";
    public const string OneDrivePathBlocked = "onedrive_path_blocked";
    public const string OneDrivePolicyDenied = "onedrive_policy_denied";
    public const string OneDriveIdempotencyConflict = "onedrive_idempotency_conflict";
    public const string OneDriveConfigConflict = "onedrive_config_conflict";
    public const string OneDriveLeaseConflict = "onedrive_lease_conflict";
    public const string OneDriveContentChanged = "onedrive_content_changed";
    public const string OneDriveHydrationTimeout = "onedrive_hydration_timeout";
    public const string OneDriveDehydrationTimeout = "onedrive_dehydration_timeout";
    public const string OneDriveHydrationFailed = "onedrive_hydration_failed";
    public const string OneDriveDehydrationFailed = "onedrive_dehydration_failed";
    public const string OneDriveVerificationFailed = "onedrive_verification_failed";
}
